ALTER TABLE orders ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_window TSTZRANGE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;


ALTER TABLE payment ADD COLUMN IF NOT EXISTS payment_details JSONB;
ALTER TABLE payment ADD COLUMN IF NOT EXISTS fraud_flags TEXT[];
ALTER TABLE payment ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER;


ALTER TABLE product_element ADD COLUMN IF NOT EXISTS stock_level INTEGER;
ALTER TABLE product_element ADD COLUMN IF NOT EXISTS supplier_id INTEGER;


ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS ip_address INET;