services:
  postgres:
    build: .
    container_name: pg_course
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./full_dmp.sql:/docker-entrypoint-initdb.d/full_dmp.sql

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command:
      - "migrate"
      - "-baselineOnMigrate=true"
    volumes:
      - ./db/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/shopdb
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: admin_pass
      FLYWAY_BASELINE_VERSION: 1
      FLYWAY_BASELINE_DESCRIPTION: "Initial baseline"
      FLYWAY_SCHEMAS: public

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres_exporter
    environment:
      # Используем ваши существующие креды
      DATA_SOURCE_NAME: "postgresql://admin:admin_pass@postgres:5432/shopdb?sslmode=disable"
    volumes:
      - ./monitoring/queries.yaml:/queries.yaml:ro
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_statements"
      - "--collector.stat_user_tables"
      - "--collector.stat_user_indexes"
      - "--collector.pg_stat_activity"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"  # Для перезагрузки конфига без рестарта
    depends_on:
      - postgres_exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Смените при первом входе!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pg_data:
  prom_data:
  grafana_data: